[package]
name = "advent-23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
regex = "1.10.2"
winnow = "0.5.26"

[[bench]]
name = "day_04"
harness = false